init
louis-nwosu/gotahia pull request #1
Opened 2021-06-08 12:18 UTC by louis-nwosu

2021-06-09 14:16 UTC, ChidiOkpala requested changes

2021-06-09 14:16 UTC, ChidiOkpala commented on src/components/home/productCard.tsx
> +import { notification } from "antd";
Combine the import in line 2 and 3

2021-06-11 01:14 UTC, louis-nwosu commented on src/App.tsx
> +import { BrowserRouter, Switch, Route } from "react-router-dom";
alright...i'll change up everything to match the teams standards

2021-06-11 01:14 UTC, louis-nwosu commented on src/components/cart/cartCard.tsx
> +  fn: (id: number) => void;
noted

2021-06-11 01:14 UTC, louis-nwosu commented on src/components/cart/cartCard.tsx
> +      message: ``,
noted...i'll keep that in mind

2021-06-11 01:15 UTC, louis-nwosu commented on src/components/cart/cartCard.tsx
> +            src={`${image}`}
i tried to but it was giving a weird error message...i'll look into it again

2021-06-11 01:16 UTC, louis-nwosu commented on src/components/cart/cartCard.tsx
> +    <React.Fragment>
okay....the fragment is only a matter of personal preference..but i'll switch up to match teams standards

2021-06-11 01:16 UTC, louis-nwosu commented on src/components/cart/cartDisplay.tsx
> +  console.log(cartArr);
lol....noted..sorry about that

2021-06-11 01:16 UTC, louis-nwosu commented on src/components/home/footer.jsx
> +export default Footer;
i see...okay

2021-06-11 01:17 UTC, louis-nwosu commented on src/components/home/productCard.tsx
> +import { notification } from "antd";
noted...i'll change that right away

2021-08-20 06:13 UTC, merged